import 'question.dart';

List<McqQuestion> EnglishTutNumber = [
  McqQuestion(
      questionType: '4MI',
      questionText: 'छवि में संख्या को सही ढंग से पहचानें। ',
      imageString: 'assets/beginnerImages/numbers/t1.png',
      optionA: 'one',
      optionB: 'zero',
      optionC: 'two',
      optionD: 'three',
      answer: 'zero'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'छवि में संख्या को सही ढंग से पहचानें। ',
      imageString: 'assets/beginnerImages/numbers/t2.png',
      optionA: 'eight',
      optionB: 'seven',
      optionC: 'one',
      optionD: 'five',
      answer: 'one'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'छवि में संख्या को सही ढंग से पहचानें। ',
      imageString: 'assets/beginnerImages/numbers/t3.png',
      optionA: 'three',
      optionB: 'one',
      optionC: 'six',
      optionD: 'two',
      answer: 'two'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'दी गई संख्या की सही पहचान करें।',
      imageString: 'assets/beginnerImages/numbers/t4.png',
      optionA: 'one',
      optionB: 'two',
      optionC: 'three',
      optionD: 'five',
      answer: 'three'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'दी गई संख्या की सही पहचान करें।',
      imageString: 'assets/beginnerImages/numbers/t5.png',
      optionA: 'forty-one',
      optionB: 'fourteen',
      optionC: 'eighty-three',
      optionD: 'Seventeen',
      answer: 'fourteen'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'दी गई संख्या की सही पहचान करें।',
      imageString: 'assets/beginnerImages/numbers/t6.png',
      optionA: 'five',
      optionB: 'thirty seven',
      optionC: 'fifty-five',
      optionD: 'forty-five',
      answer: 'fifty-five'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'दी गई संख्या की सही पहचान करें।',
      imageString: 'assets/beginnerImages/numbers/t7.png',
      optionA: 'two',
      optionB: 'five',
      optionC: 'nine',
      optionD: 'seven',
      answer: 'nine'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'दी गई संख्या की सही पहचान करें।',
      imageString: 'assets/beginnerImages/numbers/t8.png',
      optionA: 'forty-five',
      optionB: 'eighty-four',
      optionC: 'sixty-nine',
      optionD: 'forty-eight',
      answer: 'sixty-nine'),
];
List<McqQuestion> EnglishQuizNumber = [
  McqQuestion(
      questionType: '4MI',
      questionText: 'छवि में संख्या को सही ढंग से पहचानें',
      imageString: 'assets/beginnerImages/numbers/q1.png',
      optionA: 'one',
      optionB: 'zero',
      optionC: 'two',
      optionD: 'three',
      answer: 'two'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'सात को अंग्रेजी में क्या कहते हैं?',
      imageString: '',
      optionA: 'eight',
      optionB: 'seven',
      optionC: 'six',
      optionD: 'five',
      answer: 'seven'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'पांच से पहले कौन सी संख्या आती है?',
      imageString: '',
      optionA: 'Three',
      optionB: 'one',
      optionC: 'six',
      optionD: 'four',
      answer: 'four'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'दी गई संख्या की सही पहचान करें',
      imageString: 'assets/beginnerImages/numbers/q4.png',
      optionA: 'one',
      optionB: 'two',
      optionC: 'zero',
      optionD: 'five',
      answer: 'five'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'अस्सी को अंग्रेजी में क्या कहते हैं?',
      imageString: '',
      optionA: 'forty-five',
      optionB: 'eighty-four',
      optionC: 'eighty-three',
      optionD: 'forty-eight',
      answer: 'eighty-three'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'दी गई संख्या को पहचानें?',
      imageString: 'assets/beginnerImages/numbers/q6.png',
      optionA: 'five',
      optionB: 'thirty-seven',
      optionC: 'twenty-seven',
      optionD: 'forty-five',
      answer: 'twenty-seven'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'कौन सी संख्या आठ से बड़ी है?',
      imageString: '',
      optionA: 'two',
      optionB: 'five',
      optionC: 'nine',
      optionD: 'seven',
      answer: 'nine'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'दी गई संख्या को पहचानें?',
      imageString: 'assets/beginnerImages/numbers/q8.png',
      optionA: 'forty-five',
      optionB: 'eighty-four',
      optionC: 'twenty seven',
      optionD: 'forty-eight',
      answer: 'forty-eight'),
];

List<McqQuestion> EnglishTutAnimals = [
  McqQuestion(
      questionType: '4MI',
      questionText: 'यह कौन सा जानवर है?',
      imageString: 'assets/beginnerImages/animals/t1.png',
      optionA: 'Dog',
      optionB: 'Cat',
      optionC: 'Leopard',
      optionD: 'Tiger',
      answer: 'Dog'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'यह कौन सा जानवर है?',
      imageString: 'assets/beginnerImages/animals/t2.png',
      optionA: 'Dog',
      optionB: 'Cat',
      optionC: 'Leopard',
      optionD: 'Lion',
      answer: 'Cat'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'यह कौन सा जानवर है?',
      imageString: 'assets/beginnerImages/animals/t3.png',
      optionA: 'Leopard',
      optionB: 'Lion',
      optionC: 'Tiger',
      optionD: 'Whale',
      answer: 'Leopard'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'यह कौन सा जानवर है?',
      imageString: 'assets/beginnerImages/animals/t4.png',
      optionA: 'Leopard',
      optionB: 'Whale',
      optionC: 'Tiger',
      optionD: 'Parrot',
      answer: 'Tiger'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'यह कौन सा जानवर है?',
      imageString: 'assets/beginnerImages/animals/t5.png',
      optionA: 'Lion',
      optionB: 'Leopard',
      optionC: 'Elephant',
      optionD: 'Dog',
      answer: 'Elephant'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'यह कौन सा जानवर है?',
      imageString: 'assets/beginnerImages/animals/t6.png',
      optionA: 'Crocodile',
      optionB: 'Leopard',
      optionC: 'Tiger',
      optionD: 'Cat',
      answer: 'Crocodile'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'यह कौन सा जानवर है?',
      imageString: 'assets/beginnerImages/animals/t7.png',
      optionA: 'Dog',
      optionB: 'Tiger',
      optionC: 'Lion',
      optionD: 'Whale',
      answer: 'Whale'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'यह कौन सा पक्षी है?',
      imageString: 'assets/beginnerImages/animals/t8.png',
      optionA: 'Leopard',
      optionB: 'Parrot',
      optionC: 'Cat',
      optionD: 'Dog',
      answer: 'Parrot'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'यह कौन सा पक्षी है?',
      imageString: 'assets/beginnerImages/animals/t9.png',
      optionA: 'Parrot',
      optionB: 'Leopard',
      optionC: 'Penguin',
      optionD: 'Dog',
      answer: 'Penguin'),
];
List<McqQuestion> EnglishQuizAnimals = [
  McqQuestion(
      questionType: '4MI',
      questionText: 'जानवर की पहचान करें',
      imageString: 'assets/beginnerImages/animals/q1.png',
      optionA: 'Tiger',
      optionB: 'Leopard',
      optionC: 'Duck',
      optionD: 'Elephant',
      answer: 'Elephant'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'कौन सा जानवर अंडे देता है',
      imageString: '',
      optionA: 'Crocodile',
      optionB: 'Tiger',
      optionC: 'Lion',
      optionD: 'Elephant',
      answer: 'Crocodile'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'तेंदुए का अंग्रेजी नाम दें-',
      imageString: '',
      optionA: 'Leopard',
      optionB: 'Prawns',
      optionC: 'Blue Whale',
      optionD: 'Cat',
      answer: 'Leopard'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'विषम को पहचानें:',
      imageString: '',
      optionA: 'Tiger',
      optionB: 'Dog',
      optionC: 'Whale',
      optionD: 'cat',
      answer: 'Whale'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'निम्नलिखित में से कौन सा पालतू जानवरों के लिए अच्छा है?',
      imageString: '',
      optionA: 'Dog',
      optionB: 'Tiger',
      optionC: 'Lion',
      optionD: 'Whale',
      answer: 'Dog'),
];

List<McqQuestion> EnglishTutGreetings = [
  McqQuestion(
      questionType: '3MNI',
      questionText:
          'औपचारिक व्यावसायिक बैठक के लिए कौन सा अभिवादन सर्वोत्तम है?',
      imageString: '',
      optionA: 'Hi',
      optionB: 'Hey',
      optionC: 'Nice to meet you',
      optionD: '',
      answer: 'Nice to meet you'),
  McqQuestion(
      questionType: '3MNI',
      questionText:
          'अगर आप किसी को रात में छोड़कर जा रहे हैं, तो आप यह कहकर उनका अभिवादन कर सकते हैं',
      imageString: '',
      optionA: 'Good night',
      optionB: 'Good morning',
      optionC: 'Good evening',
      optionD: '',
      answer: 'Good night'),
  McqQuestion(
      questionType: '3MNI',
      questionText: 'अलविदा का समानार्थी',
      imageString: '',
      optionA: 'See you later',
      optionB: 'Goodbye',
      optionC: 'Nice to meet you',
      optionD: '',
      answer: 'See you later'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'कौन सा अभिवादन कर रहा है?',
      imageString: 'assets/beginnerImages/greetings/t4.png',
      optionA: 'Hi',
      optionB: 'Bye',
      optionC: 'See you tommorow',
      optionD: 'So long',
      answer: 'Hi'),
  McqQuestion(
      questionType: '3MI',
      questionText: 'समय के साथ सही अभिवादन का मिलान करें',
      imageString: 'assets/beginnerImages/greetings/t5.png',
      optionA: 'Good night',
      optionB: 'Good afternoon',
      optionC: 'Good morning',
      optionD: '',
      answer: 'Good night'),
];
List<McqQuestion> EnglishQuizGreetings = [
  McqQuestion(
      questionType: '4MNI',
      questionText: '1.	अनुवाद - अच्छा काम',
      imageString: '',
      optionA: 'Good job',
      optionB: 'Hello',
      optionC: 'Nice to meet you',
      optionD: 'Good morning',
      answer: 'Good job'),
  McqQuestion(
      questionType: '4MNI',
      questionText: '2.	प्रश्न का उत्तर दें- \'How are you\'?\’',
      imageString: '',
      optionA: 'Good Afternoon',
      optionB: 'I’m good',
      optionC: 'Thank you',
      optionD: 'Congratulations',
      answer: 'I’m good'),
  McqQuestion(
      questionType: '4MNI',
      questionText: '3.	हम कैसे माफी मांगें?',
      imageString: '',
      optionA: 'Thanks',
      optionB: 'I’m sorry',
      optionC: 'Yes',
      optionD: 'Welcome',
      answer: 'I’m sorry'),
  McqQuestion(
      questionType: '4MI',
      questionText: '4.	वे क्या कर रहे हैं?',
      imageString: 'assets/beginnerImages/greetings/q4.png',
      optionA: 'Greeting',
      optionB: 'Fighting',
      optionC: 'Ignoring',
      optionD: 'Playing',
      answer: 'Greeting'),
  McqQuestion(
      questionType: '4MNI',
      questionText:
          '5.	संबंधित क्रम में बधाई निर्दिष्ट करें: रात, दोपहर, सुबह ',
      imageString: '',
      optionA: 'Good Morning, Good afternoon, Good Night',
      optionB: 'Good Afternoon, Good Morning, Good Night',
      optionC: 'Good Night, Good afternoon, Good Morning',
      optionD: 'Good Night, Good Morning, Good afternoon',
      answer: 'Good Morning, Good afternoon, Good Night'),
];

List<McqQuestion> EnglishTutFamily = [
  McqQuestion(
      questionType: '4MNI',
      questionText: 'पिता, माता, बहन मेरे हैं',
      imageString: '',
      optionA: 'Parents',
      optionB: 'Children',
      optionC: 'Family',
      optionD: 'Grandparents',
      answer: 'Family'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'मेरे एक पिता और माता हैं। वे मेरे हैं',
      imageString: '',
      optionA: 'Family',
      optionB: 'Parents',
      optionC: 'Grandparents',
      optionD: 'Children',
      answer: 'Parents'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'वह श्रीमती एका हैं। वह है मेरी',
      imageString: 'assets/beginnerImages/family/t3.png',
      optionA: 'Mother',
      optionB: 'Father',
      optionC: 'Grandmother',
      optionD: 'Grandfather',
      answer: 'Grandmother'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'वो, मेरी…., बूढ़ी है',
      imageString: '',
      optionA: 'Grandchildren',
      optionB: 'Grandfather',
      optionC: 'Grandmother',
      optionD: 'Grandparents',
      answer: 'Grandmother'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'फातूर फिकरी का है …',
      imageString: 'assets/beginnerImages/family/t5.png',
      optionA: 'Son',
      optionB: 'Cousin',
      optionC: 'Niece',
      optionD: 'Nephew',
      answer: 'Nephew'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'सेली फिकरी कि है …',
      imageString: 'assets/beginnerImages/family/t6.png',
      optionA: 'Brother',
      optionB: 'Father',
      optionC: 'Sister',
      optionD: 'Niece',
      answer: 'Sister'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'मिस्टर फिकरी फतुर की है …',
      imageString: 'assets/beginnerImages/family/t7.png',
      optionA: 'Father',
      optionB: 'Mother',
      optionC: 'Uncle',
      optionD: 'Aunt',
      answer: 'Uncle'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'श्रीमती जका फतुर की हैं …',
      imageString: 'assets/beginnerImages/family/t8.png',
      optionA: 'Aunt',
      optionB: 'Sister',
      optionC: 'Grandmother',
      optionD: 'Mother',
      answer: 'Grandmother'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'श्रीमती रोजी फतुर की हैं …',
      imageString: 'assets/beginnerImages/family/t9.png',
      optionA: 'Aunt',
      optionB: 'Mother',
      optionC: 'Sister',
      optionD: 'Grandmother',
      answer: 'Mother'),
];
List<McqQuestion> EnglishQuizFamily = [
  McqQuestion(
      questionType: '4MNI',
      questionText:
          'सीमा से मेरा क्या संबंध है, यदि सीमा मेरे पिता की बेटी है?',
      imageString: '',
      optionA: 'Sister',
      optionB: 'Wife',
      optionC: 'Husband',
      optionD: 'Daughter',
      answer: 'Sister'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'आपके चाचा की पत्नी से आपका क्या संबंध है?',
      imageString: '',
      optionA: 'Aunt',
      optionB: 'Sister',
      optionC: 'Mother',
      optionD: 'Daughter',
      answer: 'Aunt'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'छवि में छोटे बच्चे के लिए यह आदमी कौन है?',
      imageString: 'assets/beginnerImages/family/q3.png',
      optionA: 'Wife',
      optionB: 'Daughter',
      optionC: 'Daughter-in-law',
      optionD: 'Grandson',
      answer: 'Daughter'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'मेरी माँ के पति की एक बहन है, उसका मुझसे क्या रिश्ता है?',
      imageString: '',
      optionA: 'Nephew',
      optionB: 'Son',
      optionC: 'Grandson',
      optionD: 'Friend',
      answer: 'Nephew'),
];

List<McqQuestion> EnglishTutColors = [
  McqQuestion(
      questionType: '4MI',
      questionText: 'यह कौन सा रंग है?',
      imageString: 'assets/beginnerImages/colors/t1.png',
      optionA: 'Red',
      optionB: 'Green',
      optionC: 'Blue',
      optionD: 'Yellow',
      answer: 'Blue'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'यह कौन सा रंग है?',
      imageString: 'assets/beginnerImages/colors/t2.png',
      optionA: 'Red',
      optionB: 'Green',
      optionC: 'Blue',
      optionD: 'Yellow',
      answer: 'Red'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'यह कौन सा रंग है?',
      imageString: 'assets/beginnerImages/colors/t3.png',
      optionA: 'Red',
      optionB: 'Green',
      optionC: 'Blue',
      optionD: 'Yellow',
      answer: 'Green'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'यह कौन सा रंग है?',
      imageString: 'assets/beginnerImages/colors/t4.png',
      optionA: 'Red',
      optionB: 'Green',
      optionC: 'Blue',
      optionD: 'Yellow',
      answer: 'Yellow'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'यह कौन सा रंग है?',
      imageString: 'assets/beginnerImages/colors/t5.png',
      optionA: 'Orange',
      optionB: 'Violet',
      optionC: 'Blue',
      optionD: 'Yellow',
      answer: 'Violet'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'यह कौन सा रंग है?',
      imageString: 'assets/beginnerImages/colors/t6.png',
      optionA: 'Violet',
      optionB: 'Green',
      optionC: 'Pink',
      optionD: 'Yellow',
      answer: 'Pink'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'यह कौन सा रंग है?',
      imageString: 'assets/beginnerImages/colors/t7.png',
      optionA: 'Orange',
      optionB: 'Green',
      optionC: 'Blue',
      optionD: 'Yellow',
      answer: 'Orange'),
];
List<McqQuestion> EnglishQuizColors = [
  McqQuestion(
      questionType: '4MI',
      questionText: 'लड़की के बालों का रंग क्या है?',
      imageString: 'assets/beginnerImages/colors/q1.png',
      optionA: 'Red',
      optionB: 'Green',
      optionC: 'Black',
      optionD: 'Yellow',
      answer: 'Black'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'गेंद का रंग क्या है?',
      imageString: 'assets/beginnerImages/colors/q2.png',
      optionA: 'Red',
      optionB: 'Orange',
      optionC: 'Blue',
      optionD: 'Yellow',
      answer: 'Orange'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'जूते का रंग क्या है?',
      imageString: 'assets/beginnerImages/colors/q3.jpg',
      optionA: 'Red',
      optionB: 'Green',
      optionC: 'Blue',
      optionD: 'Yellow',
      answer: 'Blue'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'फूल का रंग क्या है?',
      imageString: 'assets/beginnerImages/colors/q4.png',
      optionA: 'Red',
      optionB: 'Green',
      optionC: 'Blue',
      optionD: 'Yellow',
      answer: 'Yellow'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'कार का रंग क्या है?',
      imageString: 'assets/beginnerImages/colors/q5.png',
      optionA: 'Red',
      optionB: 'Violet',
      optionC: 'Blue',
      optionD: 'Yellow',
      answer: 'Red'),
];
