import 'question.dart';

List<McqQuestion> HindiTutNumber = [
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the number in the image correctly.',
      imageString: 'assets/beginnerImages/numbers/t1.png',
      optionA: 'एक',
      optionB: 'शून्य',
      optionC: 'दो',
      optionD: 'तीन',
      answer: 'शून्य'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the number in the image correctly.',
      imageString: 'assets/beginnerImages/numbers/t2.png',
      optionA: 'आठ',
      optionB: 'सात',
      optionC: 'एक',
      optionD: 'पांच',
      answer: 'एक'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the number in the image correctly.',
      imageString: 'assets/beginnerImages/numbers/t3.png',
      optionA: 'तीन',
      optionB: 'एक',
      optionC: 'छह',
      optionD: 'दो',
      answer: 'दो'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the number in the image correctly.',
      imageString: 'assets/beginnerImages/numbers/t4.png',
      optionA: 'एक',
      optionB: 'दो',
      optionC: 'तीन',
      optionD: 'पांच',
      answer: 'तीन'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the given number.',
      imageString: 'assets/beginnerImages/numbers/t5.png',
      optionA: 'इकतालीस',
      optionB: 'चौदह',
      optionC: 'अस्सी-तीन',
      optionD: 'सत्रह',
      answer: 'चौदह'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the given number.',
      imageString: 'assets/beginnerImages/numbers/t6.png',
      optionA: 'पांच',
      optionB: 'सैंतीस',
      optionC: 'पचपन ',
      optionD: 'पैंतालीस',
      answer: 'पैंतालीस'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the given number.',
      imageString: 'assets/beginnerImages/numbers/t7.png',
      optionA: 'दो',
      optionB: 'पांच',
      optionC: 'नौ',
      optionD: 'सात',
      answer: 'नौ'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the given number.',
      imageString: 'assets/beginnerImages/numbers/t8.png',
      optionA: 'पैंतालीस',
      optionB: 'चौरासी',
      optionC: 'उनहत्तर',
      optionD: 'अड़तालीस',
      answer: 'उनहत्तर'),
];
List<McqQuestion> HindiQuizNumber = [
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the number in the image correctly.',
      imageString: 'assets/beginnerImages/numbers/q1.png',
      optionA: 'एक',
      optionB: 'शून्य',
      optionC: 'दो',
      optionD: 'तीन',
      answer: 'दो'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'What is Seven called in Hindi?',
      imageString: '',
      optionA: 'आठ',
      optionB: 'सात',
      optionC: 'छह',
      optionD: 'पांच',
      answer: 'सात'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'Which number comes before Five?',
      imageString: '',
      optionA: 'तीन',
      optionB: 'एक',
      optionC: 'छह',
      optionD: 'चार',
      answer: 'चार'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Correctly identify the given number.',
      imageString: 'assets/beginnerImages/numbers/q4.png',
      optionA: 'एक',
      optionB: 'दो',
      optionC: 'पांच',
      optionD: 'शून्य',
      answer: 'पांच'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'What is Eighty Three called in Hindi?',
      imageString: '',
      optionA: 'पैंतालीस',
      optionB: 'चौरासी',
      optionC: 'तिरासी',
      optionD: 'अड़तालीस',
      answer: 'तिरासी'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the given number.',
      imageString: 'assets/beginnerImages/numbers/q6.png',
      optionA: 'पांच',
      optionB: 'सैंतीस',
      optionC: 'सत्ताईस',
      optionD: 'पैंतालीस',
      answer: 'सत्ताईस'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'Which number is greater than Eight?',
      imageString: '',
      optionA: 'दो',
      optionB: 'पांच',
      optionC: 'नौ',
      optionD: 'सात',
      answer: 'नौ'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which bird is this?',
      imageString: 'assets/beginnerImages/numbers/q8.png',
      optionA: 'पैंतालीस',
      optionB: 'चौरासी',
      optionC: 'सत्ताईस',
      optionD: 'अड़तालीस',
      answer: 'अड़तालीस'),
];

List<McqQuestion> HindiTutAnimals = [
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which animal is this?',
      imageString: 'assets/beginnerImages/animals/t1.png',
      optionA: 'कुत्ता',
      optionB: 'बिल्ली',
      optionC: 'तेंदुआ',
      optionD: 'बाघ',
      answer: 'कुत्ता'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which animal is this?',
      imageString: 'assets/beginnerImages/animals/t2.png',
      optionA: 'कुत्ता',
      optionB: 'बिल्ली',
      optionC: 'तेंदुआ',
      optionD: 'सिंह',
      answer: 'बिल्ली'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which animal is this?',
      imageString: 'assets/beginnerImages/animals/t3.png',
      optionA: 'तेंदुआ',
      optionB: 'सिंह',
      optionC: 'बाघ',
      optionD: 'व्हेल',
      answer: 'तेंदुआ'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which animal is this?',
      imageString: 'assets/beginnerImages/animals/t4.png',
      optionA: 'तेंदुआ',
      optionB: 'व्हेल',
      optionC: 'बाघ',
      optionD: 'तोता',
      answer: 'तोता'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which animal is this?',
      imageString: 'assets/beginnerImages/animals/t5.png',
      optionA: 'सिंह',
      optionB: 'तेंदुआ',
      optionC: 'हाथी',
      optionD: 'कुत्ता',
      answer: 'हाथी'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which animal is this?',
      imageString: 'assets/beginnerImages/animals/t6.png',
      optionA: 'मगरमच्छ',
      optionB: 'तेंदुआ',
      optionC: 'बाघ',
      optionD: 'बिल्ली',
      answer: 'बिल्ली'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which animal is this?',
      imageString: 'assets/beginnerImages/animals/t7.png',
      optionA: 'कुत्ता',
      optionB: 'बाघ',
      optionC: 'सिंह',
      optionD: 'व्हेल',
      answer: 'व्हेल'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which bird is this?',
      imageString: 'assets/beginnerImages/animals/t8.png',
      optionA: 'तेंदुआ',
      optionB: 'तोता',
      optionC: 'बिल्ली',
      optionD: 'कुत्ता',
      answer: 'तोता'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which bird is this?',
      imageString: 'assets/beginnerImages/animals/t9.png',
      optionA: 'तोता',
      optionB: 'तेंदुआ',
      optionC: 'पेंगुइन',
      optionD: 'कुत्ता',
      answer: 'पेंगुइन'),
];
List<McqQuestion> HindiQuizAnimals = [
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which animal is this?',
      imageString: 'assets/beginnerImages/animals/q1.png',
      optionA: 'बाघ',
      optionB: 'तेंदुआ',
      optionC: 'बिल्ली',
      optionD: 'हाथी',
      answer: 'हाथी'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'Which animal lays eggs?',
      imageString: '',
      optionA: 'मगरमच्छ',
      optionB: 'बाघ',
      optionC: 'सिंह',
      optionD: 'हाथी',
      answer: 'मगरमच्छ'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'Hindi name of the Leopard ',
      imageString: '',
      optionA: 'तेंदुआ',
      optionB: 'झींगे',
      optionC: 'बिल्ली',
      optionD: 'व्हेल',
      answer: 'तेंदुआ'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'Odd one out:',
      imageString: '',
      optionA: 'तेंदुआ',
      optionB: 'व्हेल',
      optionC: 'बाघ',
      optionD: 'कुत्ता',
      answer: 'व्हेल'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'Which of the following will be good pet?',
      imageString: '',
      optionA: 'सिंह',
      optionB: 'तेंदुआ',
      optionC: 'व्हेल',
      optionD: 'कुत्ता',
      answer: 'कुत्ता'),
];

List<McqQuestion> HindiTutGreetings = [
  McqQuestion(
      questionType: '3MNI',
      questionText: 'Which greeting is best for a formal business meeting?',
      imageString: '',
      optionA: 'नमस्ते',
      optionB: 'अरे',
      optionC: 'आप से मिलकर अच्छा लगा',
      optionD: '',
      answer: 'आप से मिलकर अच्छा लगा'),
  McqQuestion(
      questionType: '3MNI',
      questionText:
          'If you leaving someone at night, you can greet them by saying',
      imageString: '',
      optionA: 'शुभ रात्रि',
      optionB: 'शुभ प्रभात',
      optionC: 'सुसंध्या',
      optionD: '',
      answer: 'शुभ रात्रि'),
  McqQuestion(
      questionType: '3MNI',
      questionText: 'Synonymous of goodbye',
      imageString: '',
      optionA: 'See you later',
      optionB: 'Goodbye',
      optionC: 'Nice to meet you',
      optionD: '',
      answer: 'See you later'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which one is greeting?',
      imageString: 'assets/beginnerImages/greetings/t4.png',
      optionA: 'नमस्ते',
      optionB: 'अलविदा',
      optionC: 'आप से कल मिलता हूं',
      optionD: 'बहुत लंबा',
      answer: 'नमस्ते'),
  McqQuestion(
      questionType: '3MI',
      questionText: 'Match the correct greetings with the time',
      imageString: 'assets/beginnerImages/greetings/t5.png',
      optionA: 'शुभ रात्रि',
      optionB: 'सुसंध्या',
      optionC: 'शुभ प्रभात',
      optionD: '',
      answer: 'शुभ प्रभात'),
];
List<McqQuestion> HindiQuizGreetings = [
  McqQuestion(
      questionType: '4MNI',
      questionText: 'Translate – Good job',
      imageString: '',
      optionA: 'अच्छा काम',
      optionB: 'नमस्ते',
      optionC: 'आप से मिलकर अच्छा लगा',
      optionD: 'सुबह बख़ैर',
      answer: 'अच्छा काम'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'Answer the question-‘How are you?’',
      imageString: '',
      optionA: 'नमस्कार',
      optionB: 'मैं अच्छा हूँ',
      optionC: 'शुक्रिया',
      optionD: 'बधाई हो',
      answer: 'मैं अच्छा हूँ'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'How do we apologize?',
      imageString: '',
      optionA: 'शुक्रिया',
      optionB: 'मुझे क्षमा करें',
      optionC: 'हां ',
      optionD: 'स्वागत',
      answer: 'मुझे क्षमा करें'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'What are they doing?',
      imageString: 'assets/beginnerImages/greetings/q4.png',
      optionA: 'शुभकामना',
      optionB: 'लड़ाई',
      optionC: 'की उपेक्षा',
      optionD: 'खेल रहे हैं',
      answer: 'शुभकामना'),
  McqQuestion(
      questionType: '4MNI',
      questionText:
          '5.	Specify the greetings in respective orders:Night, Noon, Morning',
      imageString: '',
      optionA: 'शुभ प्रभात, नमस्कार, शुभ रात्रि',
      optionB: 'नमस्कार, शुभ प्रभात, शुभ रात्रि',
      optionC: 'शुभ रात्रि, नमस्कार, शुभ प्रभात',
      optionD: 'शुभ रात्रि, शुभ प्रभात, नमस्कार',
      answer: 'शुभ प्रभात, नमस्कार, शुभ रात्रि'),
];

List<McqQuestion> HindiTutFamily = [
  McqQuestion(
      questionType: '4MNI',
      questionText: 'Father,mother, sister are my',
      imageString: '',
      optionA: 'माता - पिता',
      optionB: 'बच्चे',
      optionC: 'परिवार',
      optionD: 'दादा दादी',
      answer: 'परिवार'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'I have a father and mother. They are my',
      imageString: '',
      optionA: 'परिवार',
      optionB: 'माता - पिता',
      optionC: 'दादा दादी',
      optionD: 'बच्चे',
      answer: 'माता - पिता'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'She is Mrs. Eka. She is my',
      imageString: 'assets/beginnerImages/family/t3.png',
      optionA: 'मां',
      optionB: 'पिता जी',
      optionC: 'दादी मा',
      optionD: 'दादा',
      answer: 'दादी मा'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'She, my …., is old',
      imageString: '',
      optionA: 'बेटा',
      optionB: 'दादा',
      optionC: 'दादी मा',
      optionD: 'दादा दादी',
      answer: 'दादी मा'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Fatur is Fikri’s…',
      imageString: 'assets/beginnerImages/family/t5.png',
      optionA: 'बेटा',
      optionB: 'चचेरा भाई',
      optionC: 'भांजी',
      optionD: 'भतीजा',
      answer: 'भतीजा'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Seli is Fatur’s…',
      imageString: 'assets/beginnerImages/family/t6.png',
      optionA: 'भाई',
      optionB: 'पिता जी',
      optionC: 'बहन',
      optionD: 'भांजी',
      answer: 'बहन'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Mr. Fikri is Fatur’s…',
      imageString: 'assets/beginnerImages/family/t7.png',
      optionA: 'पिता जी',
      optionB: 'मां',
      optionC: 'चाचा',
      optionD: 'चाची',
      answer: 'चाचा'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Mrs. Jaka is Fatur’s …',
      imageString: 'assets/beginnerImages/family/t8.png',
      optionA: 'चाची',
      optionB: 'बहन',
      optionC: 'दादी मा',
      optionD: 'मां',
      answer: 'दादी मा'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Mrs. Rosi is Fatur’s…',
      imageString: 'assets/beginnerImages/family/t9.png',
      optionA: 'चाची',
      optionB: 'मां',
      optionC: 'बहन',
      optionD: 'दादी मा',
      answer: 'मां'),
];
List<McqQuestion> HindiQuizFamily = [
  McqQuestion(
      questionType: '4MNI',
      questionText:
          'What is my relation to Seema, if Seema is Daughter of my father?',
      optionA: 'बहन',
      optionB: 'बीवी',
      optionC: 'पति',
      optionD: 'बेटी',
      answer: 'बहन',
      imageString: ''),
  McqQuestion(
      questionType: '4MNI',
      questionText: '2.	What is your relation to your uncle’s wife?',
      optionA: 'चाची',
      optionB: 'बहन',
      optionC: 'मां',
      optionD: 'बेटी',
      imageString: '',
      answer: 'चाची'),
  McqQuestion(
      questionType: '4MI',
      questionText: '3.	Who is this man to the small kid in the image?',
      imageString: 'assets/beginnerImages/family/q3.png',
      optionA: 'बीवी',
      optionB: 'बेटी',
      optionC: 'बहू',
      optionD: 'पोता',
      answer: 'बेटी'),
  McqQuestion(
      questionType: '4MNI',
      questionText:
          '4.	My Mutter’s husband have a sister, What is her relation to me?',
      optionA: 'भतीजा',
      optionB: 'Sohn',
      imageString: '',
      optionC: 'पोता',
      optionD: 'दोस्त',
      answer: 'भतीजा'),
];

List<McqQuestion> HindiTutColour = [
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which colour is this?',
      imageString: 'assets/beginnerImages/colors/t1.png',
      optionA: 'लाल',
      optionB: 'हरा',
      optionC: 'नीला',
      optionD: 'पीला',
      answer: 'नीला'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which colour is this?',
      imageString: 'assets/beginnerImages/colors/t2.png',
      optionA: 'लाल',
      optionB: 'हरा',
      optionC: 'नीला',
      optionD: 'पीला',
      answer: 'लाल'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which colour is this?',
      imageString: 'assets/beginnerImages/colors/t3.png',
      optionA: 'लाल',
      optionB: 'हरा',
      optionC: 'नीला',
      optionD: 'पीला',
      answer: 'हरा'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which colour is this?',
      imageString: 'assets/beginnerImages/colors/t4.png',
      optionA: 'लाल',
      optionB: 'हरा',
      optionC: 'नीला',
      optionD: 'पीला',
      answer: 'पीला'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which colour is this?',
      imageString: 'assets/beginnerImages/colors/t5.png',
      optionA: 'संतरा',
      optionB: 'वायलेट',
      optionC: 'नीला',
      optionD: 'पीला',
      answer: 'वायलेट'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which colour is this?',
      imageString: 'assets/beginnerImages/colors/t6.png',
      optionA: 'वायलेट',
      optionB: 'हरा',
      optionC: 'गुलाबी',
      optionD: 'पीला',
      answer: 'गुलाबी'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which colour is this?',
      imageString: 'assets/beginnerImages/colors/t7.png',
      optionA: 'संतरा',
      optionB: 'हरा',
      optionC: 'नीला',
      optionD: 'पीला',
      answer: 'नारंगी'),
];
List<McqQuestion> HindiQuizColor = [
  McqQuestion(
      questionType: '4MI',
      questionText: 'What is the color of the girl\'s hair?',
      imageString: 'assets/beginnerImages/colors/q1.png',
      optionA: 'लाल',
      optionB: 'हरा',
      optionC: 'काला',
      optionD: 'पीला',
      answer: 'काला'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'What is the color of the ball??',
      imageString: 'assets/beginnerImages/colors/q2.png',
      optionA: 'लाल',
      optionB: 'संतरा',
      optionC: 'नीला',
      optionD: 'पीला',
      answer: 'संतरा'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'What is the color of the shoes?',
      imageString: 'assets/beginnerImages/colors/q3.png',
      optionA: 'लाल',
      optionB: 'हरा',
      optionC: 'नीला',
      optionD: 'पीला',
      answer: 'नीला'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'What is the color of the flower?',
      imageString: 'assets/beginnerImages/colors/q4.png',
      optionA: 'लाल',
      optionB: 'हरा',
      optionC: 'नीला',
      optionD: 'पीला',
      answer: 'पीला'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'What is the color of the car?',
      imageString: 'assets/beginnerImages/colors/q5.png',
      optionA: 'लाल',
      optionB: 'बैंगनी',
      optionC: 'नीला',
      optionD: 'पीला',
      answer: 'लाल'),
];
