import 'question.dart';

List<McqQuestion> SpanishTutNumber = [
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the number in the image correctly.',
      imageString: 'assets/beginnerImages/numbers/t1.png',
      optionA: 'uno',
      optionB: 'cero',
      optionC: 'dos',
      optionD: 'tres',
      answer: 'cero'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the number in the image correctly.',
      imageString: 'assets/beginnerImages/numbers/t2.png',
      optionA: 'ocho',
      optionB: 'siete',
      optionC: 'uno',
      optionD: 'cinco',
      answer: 'uno'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the number in the image correctly.',
      imageString: 'assets/beginnerImages/numbers/t3.png',
      optionA: 'tres',
      optionB: 'uno',
      optionC: 'seis',
      optionD: 'dos',
      answer: 'dos'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the number in the image correctly.',
      imageString: 'assets/beginnerImages/numbers/t4.png',
      optionA: 'uno',
      optionB: 'dos',
      optionC: 'tres',
      optionD: 'cinco',
      answer: 'tres'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the number in the image correctly.',
      imageString: 'assets/beginnerImages/numbers/t5.png',
      optionA: 'cuarenta y uno',
      optionB: 'catorce',
      optionC: 'ochenta y tres',
      optionD: 'Diecisiete',
      answer: 'catorce'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the number in the image correctly.',
      imageString: 'assets/beginnerImages/numbers/t6.png',
      optionA: 'cinco',
      optionB: 'treinta y siete',
      optionC: 'cincuenta y cinco',
      optionD: 'cuarenta y cinco',
      answer: 'cincuenta y cinco'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the number in the image correctly.',
      imageString: 'assets/beginnerImages/numbers/t7.png',
      optionA: 'dos',
      optionB: 'cinco',
      optionC: 'nueve',
      optionD: 'siete',
      answer: 'nueve'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the number in the image correctly.',
      imageString: 'assets/beginnerImages/numbers/t8.png',
      optionA: 'cuarenta y cinco',
      optionB: 'ochenta y cuatro',
      optionC: 'sesenta y nueve',
      optionD: 'cuarenta y ocho',
      answer: 'sesenta y nueve'),
];

List<McqQuestion> SpanishQuizNumber = [
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the number in the image correctly.',
      imageString: 'assets/beginnerImages/numbers/q1.png',
      optionA: 'uno',
      optionB: 'cero',
      optionC: 'dos',
      optionD: 'tres',
      answer: 'dos'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'What is Seven called in Hindi?',
      imageString: '',
      optionA: 'ocho',
      optionB: 'siete',
      optionC: 'seis',
      optionD: 'cinco',
      answer: 'siete'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'Which number comes before Five?',
      imageString: '',
      optionA: 'tres',
      optionB: 'uno',
      optionC: 'seis',
      optionD: 'cuatro',
      answer: 'cuatro'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Correctly identify the given number.',
      imageString: 'assets/beginnerImages/numbers/q4.png',
      optionA: 'uno',
      optionB: 'dos',
      optionC: 'cero',
      optionD: 'cinco',
      answer: 'cinco'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'What is Eighty Three called in Hindi?',
      imageString: '',
      optionA: 'cuarenta y cinco',
      optionB: 'ochenta y cuatro',
      optionC: 'ochenta y tres',
      optionD: 'cuarenta y ocho',
      answer: 'ochenta y tres'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Identify the given number.',
      imageString: 'assets/beginnerImages/numbers/q6.png',
      optionA: 'cinco',
      optionB: 'treinta y siete',
      optionC: 'veintisiete',
      optionD: 'cuarenta y cinco',
      answer: 'veintisiete'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'Which number is greater than Eight?',
      imageString: '',
      optionA: 'dos',
      optionB: 'cinco',
      optionC: 'nueve',
      optionD: 'siete',
      answer: 'nueve'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which bird is this?',
      imageString: 'assets/beginnerImages/numbers/q8.png',
      optionA: 'cuarenta y cinco',
      optionB: 'ochenta y cuatro',
      optionC: 'veintisiete',
      optionD: 'cuarenta y ocho',
      answer: 'cuarenta y ocho'),
];

List<McqQuestion> SpanishTutAnimals = [
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which animal is this?',
      imageString: 'assets/beginnerImages/animals/t1.png',
      optionA: 'Perro',
      optionB: 'Gato',
      optionC: 'Leopardo',
      optionD: 'Tigre',
      answer: 'Perro'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which animal is this?',
      imageString: 'assets/beginnerImages/animals/t2.png',
      optionA: 'Perro',
      optionB: 'Gato',
      optionC: 'Leopardo',
      optionD: 'León',
      answer: 'Gato'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which animal is this?',
      imageString: 'assets/beginnerImages/animals/t3.png',
      optionA: 'Leopardo',
      optionB: 'León',
      optionC: 'Tigre',
      optionD: 'Ballena',
      answer: 'Leopardo'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which animal is this?',
      imageString: 'assets/beginnerImages/animals/t4.png',
      optionA: 'Leopardo',
      optionB: 'Ballena',
      optionC: 'Tigre',
      optionD: 'Loro',
      answer: 'Tigre'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which animal is this?',
      imageString: 'assets/beginnerImages/animals/t5.png',
      optionA: 'León',
      optionB: 'Leopardo',
      optionC: 'Elefante',
      optionD: 'Perro',
      answer: 'Elefante'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which animal is this?',
      imageString: 'assets/beginnerImages/animals/t6.png',
      optionA: 'Cocodrilo',
      optionB: 'Leopardo',
      optionC: 'Tigre',
      optionD: 'Gato',
      answer: 'Cocodrilo'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which animal is this?',
      imageString: 'assets/beginnerImages/animals/t7.png',
      optionA: 'Perro',
      optionB: 'Tigre',
      optionC: 'León',
      optionD: 'Ballena',
      answer: 'Ballena'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which bird is this?',
      imageString: 'assets/beginnerImages/animals/t8.png',
      optionA: 'Loro',
      optionB: 'Leopardo',
      optionC: 'Gato',
      optionD: 'Perro',
      answer: 'Loro'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which bird is this?',
      imageString: 'assets/beginnerImages/animals/t9.png',
      optionA: 'Loro',
      optionB: 'Gato',
      optionC: 'Pingüino',
      optionD: 'Perro',
      answer: 'Pingüino'),
];

List<McqQuestion> SpanishQuizAnimals = [
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which animal is this?',
      imageString: 'assets/beginnerImages/animals/q1.png',
      optionA: 'Tigre',
      optionB: 'Leopardo',
      optionC: 'Pato',
      optionD: 'Elefante',
      answer: 'Elefante'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'Which animal lays eggs?',
      imageString: '',
      optionA: 'Cocodrilo',
      optionB: 'Tigre',
      optionC: 'León',
      optionD: 'Elefante',
      answer: 'Cocodrilo'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'Spanish name of the Leopard ',
      imageString: '',
      optionA: 'Leopardo',
      optionB: 'Langostinos',
      optionC: 'Ballena azul',
      optionD: 'Gato',
      answer: 'Leopardo'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'Odd one out:',
      imageString: '',
      optionA: 'Tigre',
      optionB: 'Perro',
      optionC: 'Ballena',
      optionD: 'Gato',
      answer: 'Ballena'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'Which of the following will be good pet?',
      imageString: '',
      optionA: 'Perro',
      optionB: 'Tigre',
      optionC: 'León',
      optionD: 'Ballena',
      answer: 'Perro'),
];

List<McqQuestion> SpanishTutGreetings = [
  McqQuestion(
      questionType: '3MNI',
      questionText: 'Which greeting is best for a formal business meeting?',
      imageString: '',
      optionA: 'Hola',
      optionB: 'Oye',
      optionC: 'Un placer conocerte',
      optionD: '',
      answer: 'Un placer conocerte'),
  McqQuestion(
      questionType: '3MNI',
      questionText: 'If you leaving someone at night, you can greet them by saying',
      imageString: '',
      optionA: 'Buenas noches',
      optionB: 'Buenos dias',
      optionC: 'Buena tarde',
      optionD: '',
      answer: 'Buenas noches'),
  McqQuestion(
      questionType: '3MNI',
      questionText: 'Synonymous of goodbye',
      imageString: '',
      optionA: 'Hasta luego',
      optionB: 'Adiós',
      optionC: 'Un placer conocerte',
      optionD: '',
      answer: 'Hasta luego'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which one is greeting?',
      imageString: 'assets/beginnerImages/greetings/t4.png',
      optionA: 'Hola',
      optionB: 'Adiós',
      optionC: 'Nos vemos mañana',
      optionD: 'Hasta la vista',
      answer: 'Hola'),
  McqQuestion(
      questionType: '3MI',
      questionText: 'Match the correct greetings with the time',
      imageString: 'assets/beginnerImages/greetings/t5.png',
      optionA: 'Buenas noches',
      optionB: 'Buenas tardes',
      optionC: 'Buenos dias',
      optionD: '',
      answer: 'Buenos dias'),
];

List<McqQuestion> SpanishQuizGreetings = [
  McqQuestion(
      questionType: '4MNI',
      questionText: 'Translate – Good job',
      imageString: '',
      optionA: 'Buen trabajo',
      optionB: 'Hola',
      optionC: 'Un placer conocerte',
      optionD: 'Buenos dias',
      answer: 'Buen trabajo'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'Answer the question-‘How are you?’',
      imageString: '',
      optionA: 'Buenas tardes',
      optionB: 'estoy bien',
      optionC: 'Gracias',
      optionD: 'Felicidades',
      answer: 'estoy bien'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'How do we apologize?',
      imageString: '',
      optionA: 'Gracias',
      optionB: 'Lo siento',
      optionC: 'sí',
      optionD: 'Bienvenido',
      answer: 'lo siento'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'What are they doing?',
      imageString: 'assets/beginnerImages/greetings/q4.png',
      optionA: 'Saludo',
      optionB: 'Luchando',
      optionC: 'Postergación',
      optionD: 'Jugando',
      answer: 'Saludo'),
  McqQuestion(
      questionType: '4MNI',
      questionText: '5.	Specify the greetings in respective orders:Night, Noon, Morning',
      imageString: '',
      optionA: 'Buenos dias, buenas tardes, buenas noches',
      optionB: 'Buenas tardes, buenos días, buenas noches',
      optionC: 'Buenas noches, buenas tardes, buenos días',
      optionD: 'Buenas noches, buenos días, buenas tardes',
      answer: 'Buenos días, buenas tardes, buenas noches'),
];

List<McqQuestion> SpanishTutFamily = [
  McqQuestion(
      questionType: '4MNI',
      questionText: 'Father,mother, sister are my',
      imageString: '',
      optionA: 'Padres',
      optionB: 'Niños',
      optionC: 'Familia',
      optionD: 'Abuelos',
      answer: 'Familia'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'I have a father and mother. They are my',
      imageString: '',
      optionA: 'Familia',
      optionB: 'Padres',
      optionC: 'Abuelos',
      optionD: 'Niños',
      answer: 'Padres'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'She is Mrs. Eka. She is my',
      imageString: 'assets/beginnerImages/family/t3.png',
      optionA: 'Madre',
      optionB: 'Padre',
      optionC: 'Abuela',
      optionD: 'Abuelo',
      answer: 'Abuela'),
  McqQuestion(
      questionType: '4MNI',
      questionText: 'She, my …., is old',
      imageString: '',
      optionA: 'Nietos',
      optionB: 'Abuelo',
      optionC: 'Abuela',
      optionD: 'Abuelos',
      answer: 'Abuela'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Fatur is Fikri’s…',
      imageString: 'assets/beginnerImages/family/t5.png',
      optionA: 'Hijo',
      optionB: 'Primo',
      optionC: 'Sobrina',
      optionD: 'Sobrino',
      answer: 'Sobrino'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Seli is Fatur’s…',
      imageString: 'assets/beginnerImages/family/t6.png',
      optionA: 'Hermano',
      optionB: 'Padre',
      optionC: 'Hermana',
      optionD: 'Sobrina',
      answer: 'Hermana'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Mr. Fikri is Fatur’s…',
      imageString: 'assets/beginnerImages/family/t7.png',
      optionA: 'Padre',
      optionB: 'Madre',
      optionC: 'Tío',
      optionD: 'Tía',
      answer: 'Tío'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Mrs. Jaka is Fatur’s …',
      imageString: 'assets/beginnerImages/family/t8.png',
      optionA: 'Tío',
      optionB: 'Hermana',
      optionC: 'Abuela',
      optionD: 'Madre',
      answer: 'Abuela'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Mrs. Rosi is Fatur’s…',
      imageString: 'assets/beginnerImages/family/t9.png',
      optionA: 'Tía',
      optionB: 'Madre',
      optionC: 'Hermana',
      optionD: 'Abuela',
      answer: 'Madre'),
];
List<McqQuestion> SpanishQuizFamily = [
  McqQuestion(
      questionType: '4MNI',
      questionText: 'What is my relation to Seema, if Seema is Daughter of my father?',
      optionA: 'Hermana',
      optionB: 'Esposa',
      optionC: 'Marido',
      optionD: 'Hija',
      answer: 'Hermana',
      imageString: ''),
  McqQuestion(
      questionType: '4MNI',
      questionText: '2.	What is your relation to your uncle’s wife?',
      optionA: 'Tía',
      optionB: 'Hermana',
      optionC: 'Madre',
      optionD: 'Hija',
      imageString: '',
      answer: 'Tía'),
  McqQuestion(
      questionType: '4MI',
      questionText: '3.	Who is this man to the small kid in the image?',
      imageString: 'assets/beginnerImages/family/q3.png',
      optionA: 'Esposa',
      optionB: 'Hija',
      optionC: 'Hijastra',
      optionD: 'Nieto',
      answer: 'Hija'),
  McqQuestion(
      questionType: '4MNI',
      questionText: '4.	My Mutter’s husband have a sister, What is her relation to me?',
      optionA: 'Sobrino',
      optionB: 'Hijo',
      imageString: '',
      optionC: 'Nieto',
      optionD: 'Amigo',
      answer: 'Sobrino'),
];

List<McqQuestion> SpanishTutColour = [
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which colour is this?',
      imageString: 'assets/beginnerImages/colors/t1.png',
      optionA: 'Rojo',
      optionB: 'Verde',
      optionC: 'Azul',
      optionD: 'Amarillo',
      answer: 'Azul'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which colour is this?',
      imageString: 'assets/beginnerImages/colors/t2.png',
      optionA: 'Rojo',
      optionB: 'Verde',
      optionC: 'Azul',
      optionD: 'Amarillo',
      answer: 'Rojo'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which colour is this?',
      imageString: 'assets/beginnerImages/colors/t3.png',
      optionA: 'Rojo',
      optionB: 'Verde',
      optionC: 'Azul',
      optionD: 'Amarillo',
      answer: 'Verde'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which colour is this?',
      imageString: 'assets/beginnerImages/colors/t4.png',
      optionA: 'Rojo',
      optionB: 'Verde',
      optionC: 'Azul',
      optionD: 'Amarillo',
      answer: 'Amarillo'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which colour is this?',
      imageString: 'assets/beginnerImages/colors/t5.png',
      optionA: 'Naranja',
      optionB: 'Violeta',
      optionC: 'Azul',
      optionD: 'Amarillo',
      answer: 'Violeta'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which colour is this?',
      imageString: 'assets/beginnerImages/colors/t6.png',
      optionA: 'Violeta',
      optionB: 'Verde',
      optionC: 'Rosa',
      optionD: 'Amarillo',
      answer: 'Rosa'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'Which colour is this?',
      imageString: 'assets/beginnerImages/colors/t7.png',
      optionA: 'Naranja',
      optionB: 'Verde',
      optionC: 'Azul',
      optionD: 'Amarillo',
      answer: 'Naranja'),
];
List<McqQuestion> SpanishQuizColor = [
  McqQuestion(
      questionType: '4MI',
      questionText: 'What is the color of the girl\'s hair?',
      imageString: 'assets/beginnerImages/colors/q1.png',
      optionA: 'Rojo',
      optionB: 'Verde',
      optionC: 'Negro',
      optionD: 'Amarillo',
      answer: 'Negro'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'What is the color of the ball??',
      imageString: 'assets/beginnerImages/colors/q2.png',
      optionA: 'Rojo',
      optionB: 'Naranja',
      optionC: 'Azul',
      optionD: 'Amarillo',
      answer: 'Naranja'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'What is the color of the shoes?',
      imageString: 'assets/beginnerImages/colors/q3.png',
      optionA: 'Rojo',
      optionB: 'Verde',
      optionC: 'Azul',
      optionD: 'Amarillo',
      answer: 'Azul'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'What is the color of the flower?',
      imageString: 'assets/beginnerImages/colors/q4.png',
      optionA: 'Rojo',
      optionB: 'Verde',
      optionC: 'Azul',
      optionD: 'Amarillo',
      answer: 'Amarillo'),
  McqQuestion(
      questionType: '4MI',
      questionText: 'What is the color of the car?',
      imageString: 'assets/beginnerImages/colors/q5.png',
      optionA: 'Rojo',
      optionB: 'Violeta',
      optionC: 'Azul',
      optionD: 'Amarillo',
      answer: 'Rojo'),
];
